### PR TITLE
Added Dockerfile for building image of gateway

### LINKED ISSUE #3: Kotlin api docker connectivity.
To do:
1. Create a dockerfile for dockerising kotlin application
2. Run it in a defined port.
3. Add kotlin to docker-compose.

### PR DESCRIPTION
**Pull request by karthi2732**
Added Dockerfile for building image of Gateway Application

### CODE REVIEW

**Comment by sunjayjeffrish** [comment]
Please add description @karthi2732 🥇

**Review by sunjayjeffrish — APPROVED** [review]
Test it in local 👍

**Comment by karthi2732** [comment]
> Test it in local 👍

Tested and it was working fine.

**Review by sunjayjeffrish — APPROVED** [review]
Nice one da 🚀 🚀 👍

**Pull request merged**
